"""add sensor_analysis

Revision ID: 6d1ec4c3deff
Revises: '96529a220a52'
Create Date: 2026-09-15 11:36:06.946188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d1ec4c3deff'
down_revision = '96529a220a52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_analysis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('sensor_name', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('persistence', sa.Float(), nullable=True),
    sa.Column('slope', sa.Float(), nullable=True),
    sa.Column('normalized_deviation', sa.Float(), nullable=True),
    sa.Column('degradation_direction', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_analysis_prediction_id'), 'sensor_analysis', ['prediction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_analysis_prediction_id'), table_name='sensor_analysis')
    op.drop_table('sensor_analysis')
    # ### end Alembic commands ###
