"""initial schema

Revision ID: 96529a220a52
Revises: None
Create Date: 2026-09-14 23:20:51.157441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96529a220a52'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unit_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('fleet_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('total_cycles', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_unit_number'), 'assets', ['unit_number'], unique=True)
    op.create_table('missions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('mission_name', sa.String(length=100), nullable=False),
    sa.Column('mission_type', sa.String(length=50), nullable=True),
    sa.Column('mission_duration', sa.Float(), nullable=False),
    sa.Column('planned_start_cycle', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missions_asset_id'), 'missions', ['asset_id'], unique=False)
    op.create_table('sensor_readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('unit_number', sa.Integer(), nullable=False),
    sa.Column('time_cycles', sa.Integer(), nullable=False),
    sa.Column('sensor_2_smooth', sa.Float(), nullable=False),
    sa.Column('sensor_3_smooth', sa.Float(), nullable=False),
    sa.Column('sensor_4_smooth', sa.Float(), nullable=False),
    sa.Column('sensor_7_smooth', sa.Float(), nullable=False),
    sa.Column('sensor_8_smooth', sa.Float(), nullable=False),
    sa.Column('sensor_9_smooth', sa.Float(), nullable=False),
    sa.Column('sensor_11_smooth', sa.Float(), nullable=False),
    sa.Column('sensor_12_smooth', sa.Float(), nullable=False),
    sa.Column('sensor_13_smooth', sa.Float(), nullable=False),
    sa.Column('sensor_14_smooth', sa.Float(), nullable=False),
    sa.Column('sensor_15_smooth', sa.Float(), nullable=False),
    sa.Column('sensor_17_smooth', sa.Float(), nullable=False),
    sa.Column('sensor_20_smooth', sa.Float(), nullable=False),
    sa.Column('sensor_21_smooth', sa.Float(), nullable=False),
    sa.Column('rul', sa.Integer(), nullable=False),
    sa.Column('rul_clipped', sa.Integer(), nullable=False),
    sa.Column('predicted_failure_TTE', sa.Integer(), nullable=True),
    sa.Column('mission_duration', sa.Float(), nullable=True),
    sa.Column('margin_of_safety', sa.Float(), nullable=True),
    sa.Column('critical_overlap_risk', sa.Boolean(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sensor_readings_asset_cycle', 'sensor_readings', ['asset_id', 'time_cycles'], unique=False)
    op.create_index(op.f('ix_sensor_readings_asset_id'), 'sensor_readings', ['asset_id'], unique=False)
    op.create_index(op.f('ix_sensor_readings_unit_number'), 'sensor_readings', ['unit_number'], unique=False)
    op.create_table('service_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cycle_at_service', sa.Integer(), nullable=False),
    sa.Column('performed_by', sa.String(length=100), nullable=True),
    sa.Column('outcome', sa.String(length=30), nullable=False),
    sa.Column('service_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_records_asset_id'), 'service_records', ['asset_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('sensor_reading_id', sa.Integer(), nullable=True),
    sa.Column('prediction_cycle', sa.Integer(), nullable=False),
    sa.Column('rul_predicted', sa.Float(), nullable=False),
    sa.Column('rul_clipped', sa.Float(), nullable=False),
    sa.Column('predicted_failure_TTE', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('predicted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sensor_reading_id'], ['sensor_readings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_asset_id'), 'predictions', ['asset_id'], unique=False)
    op.create_table('readiness_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('readiness_score', sa.Float(), nullable=False),
    sa.Column('risk_flag', sa.String(length=20), nullable=False),
    sa.Column('predicted_failure_TTE', sa.Float(), nullable=False),
    sa.Column('mission_duration', sa.Float(), nullable=False),
    sa.Column('margin_of_safety', sa.Float(), nullable=False),
    sa.Column('critical_overlap_risk', sa.Boolean(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_readiness_results_mission_id'), 'readiness_results', ['mission_id'], unique=True)
    op.create_index(op.f('ix_readiness_results_prediction_id'), 'readiness_results', ['prediction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_readiness_results_prediction_id'), table_name='readiness_results')
    op.drop_index(op.f('ix_readiness_results_mission_id'), table_name='readiness_results')
    op.drop_table('readiness_results')
    op.drop_index(op.f('ix_predictions_asset_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_service_records_asset_id'), table_name='service_records')
    op.drop_table('service_records')
    op.drop_index(op.f('ix_sensor_readings_unit_number'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_asset_id'), table_name='sensor_readings')
    op.drop_index('ix_sensor_readings_asset_cycle', table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_index(op.f('ix_missions_asset_id'), table_name='missions')
    op.drop_table('missions')
    op.drop_index(op.f('ix_assets_unit_number'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
