"""Remove ServiceRecord

Revision ID: c6d9061b43a4
Revises: '6d1ec4c3deff'
Create Date: 2026-09-15 12:17:24.261583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6d9061b43a4'
down_revision = '6d1ec4c3deff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_service_records_asset_id', table_name='service_records')
    op.drop_table('service_records')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_records',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('asset_id', sa.INTEGER(), nullable=False),
    sa.Column('service_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('cycle_at_service', sa.INTEGER(), nullable=False),
    sa.Column('performed_by', sa.VARCHAR(length=100), nullable=True),
    sa.Column('outcome', sa.VARCHAR(length=30), nullable=False),
    sa.Column('service_date', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_service_records_asset_id', 'service_records', ['asset_id'], unique=False)
    # ### end Alembic commands ###
